// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs66_QPAq0aaDjUsddWu-ea7HjoC7D3P4',
    appId: '1:698264849528:web:b55bb56edef78352c2f18d',
    messagingSenderId: '698264849528',
    projectId: 'fleet-flame-409205',
    authDomain: 'fleet-flame-409205.firebaseapp.com',
    storageBucket: 'fleet-flame-409205.appspot.com',
    measurementId: 'G-16J8GXNQZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1PyJAjYueXYvMV4lvhw7q_X1gkqaAnaY',
    appId: '1:698264849528:android:67020cba7c082957c2f18d',
    messagingSenderId: '698264849528',
    projectId: 'fleet-flame-409205',
    storageBucket: 'fleet-flame-409205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyConZX1z5czZYQQlNaho9wOXvb7QyXZIPU',
    appId: '1:698264849528:ios:44decab095915897c2f18d',
    messagingSenderId: '698264849528',
    projectId: 'fleet-flame-409205',
    storageBucket: 'fleet-flame-409205.appspot.com',
    iosClientId: '698264849528-epk3sjg19men1r0qhdjvaiobkqkkj4aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyConZX1z5czZYQQlNaho9wOXvb7QyXZIPU',
    appId: '1:698264849528:ios:58bb6e13e8cb2abec2f18d',
    messagingSenderId: '698264849528',
    projectId: 'fleet-flame-409205',
    storageBucket: 'fleet-flame-409205.appspot.com',
    iosClientId: '698264849528-aisftlu209l5bl2bou5slhasa2aqihe0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
